@bamboo_card_task_HostAddress = http://localhost:5117
@jwt_user_token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwianRpIjoiYzliMWRiNjItYjg1OC00NDQ5LTkyNzEtOThhZGI4MTI5OTdlIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoidXNlckBiYW1ib29jYXJkLmFlIiwiZXhwIjoxNzQ3MjUxMjEyLCJpc3MiOiJiYW1ib29jYXJkLmFlIiwiYXVkIjoiYmFtYm9vY2FyZC5hZSJ9.A-GGoTk3KkSfkkm8drzi5SVx-aW7bwYcIbHm1k4hepUDwyLsU9Kpm4RsBo7i1SDaYXz7rVWrNj_U3BpbbYfTRA

@jwt_admin_token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImp0aSI6IjNiZjdkZDA4LTBkYzctNGRmZC04NGQzLTFhNjgzMjY1ODgzZiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGJhbWJvb2NhcmQuYWUiLCJleHAiOjE3NDcyNTEyMTIsImlzcyI6ImJhbWJvb2NhcmQuYWUiLCJhdWQiOiJiYW1ib29jYXJkLmFlIn0.AiraS3qKcUYIigieFEpH7Fjo9KR-J8v44QYsHVMzfl5djKWsAMp-IMSxQVwJJYt9vE0J6VxaOflNQViJ_JsiAw


###
GET {{bamboo_card_task_HostAddress}}/api/exchange-rates/latest?baseCurrency=EUR
Authorization: Bearer {{jwt_user_token}}
Accept: application/json


###
GET {{bamboo_card_task_HostAddress}}/api/exchange-rates/latest
Authorization: Bearer {{jwt_user_token}}
Accept: application/json

###
POST {{bamboo_card_task_HostAddress}}/api/exchange-rates/convert
Content-Type: application/json

{
  "fromCurrency": "EUR",
  "targetCurrencies": ["USD", "AUD"]
}

###
POST {{bamboo_card_task_HostAddress}}/api/exchange-rates/convert
Content-Type: application/json

{
  "fromCurrency": "EUR",
  "targetCurrencies": ["USD", "TRY" , "PLN", "THB"]
}

###
POST {{bamboo_card_task_HostAddress}}/api/exchange-rates/historical
Content-Type: application/json

{
  "startDate": "2025-05-01",
  "endDate": "2025-05-31",
  "fromCurrency": "EUR"
}

###
GET {{bamboo_card_task_HostAddress}}/health
Accept: application/json