@bamboo_card_task_HostAddress = http://localhost:5117

GET {{bamboo_card_task_HostAddress}}/api/exchange-rates/latest?baseCurrency=EUR
Accept: application/json

###

GET https://api.frankfurter.app/latest?baseCurrency=EUR
Accept: application/json