@bamboo_card_task_HostAddress = http://localhost:5117
@jwt_user_token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwianRpIjoiYjU4MDcyMmUtYWIxZi00YmI2LWI4ZTctN2U0NGNmMDdlOTcxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoidXNlckBiYW1ib29jYXJkLmFlIiwiZXhwIjoxNzQ3MjI0NDQwLCJpc3MiOiJiYW1ib29jYXJkLmFlIiwiYXVkIjoiYmFtYm9vY2FyZC5hZSJ9.IPkZGgwFkFw204G58Gc_EGpIIYlv9DWgqx9GhisvxMi2ffwibcIi1HKJ_10f7nbMnCogwP-ExYIjDw-VqFLxqQ

@jwt_admin_token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImp0aSI6IjliYzI0NWJhLWVkYzgtNDM1NC05N2UzLTEzYTc1OTA5ZDljMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGJhbWJvb2NhcmQuYWUiLCJleHAiOjE3NDcyMjQ0NDAsImlzcyI6ImJhbWJvb2NhcmQuYWUiLCJhdWQiOiJiYW1ib29jYXJkLmFlIn0.gFMKKCzTBqJc8Rlc5QGtkZInXdYRbS0E_o7si4Kw0DGG_pROdL8n5LzJ6cYeXHCiEjNf90avpvMgTp5srNV6bg


###
GET {{bamboo_card_task_HostAddress}}/api/exchange-rates/latest?baseCurrency=EUR
Authorization: Bearer {{jwt_user_token}}
Accept: application/json


###
GET {{bamboo_card_task_HostAddress}}/api/exchange-rates/latest
Authorization: Bearer {{jwt_user_token}}
Accept: application/json

###
POST {{bamboo_card_task_HostAddress}}/api/exchange-rates/convert
Content-Type: application/json

{
  "fromCurrency": "EUR",
  "targetCurrencies": ["USD", "AUD"]
}

###
POST {{bamboo_card_task_HostAddress}}/api/exchange-rates/convert
Content-Type: application/json

{
  "fromCurrency": "EUR",
  "targetCurrencies": ["USD", "TRY" , "PLN", "THB"]
}

###
POST {{bamboo_card_task_HostAddress}}/api/exchange-rates/historical
Content-Type: application/json

{
  "startDate": "2025-05-01",
  "endDate": "2025-05-31",
  "fromCurrency": "EUR"
}